server:
  port: 8764

spring:
  application:
    name: Tax-Service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:tax;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=false
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_schema: tax
        jdbc:
          lob.non_contextual_creation: true
  flyway:
    baseline-on-migrate: true
    schemas: tax
    locations: classpath:/db/migrations
  h2:
    console:
      enabled: true
      path: /console
eureka:
  client:
    fetchRegistry: true
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug
